[[drone]]
id = 1
connected_node_ids = [3, 8, 12]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [3, 9, 13]
pdr = 0.10

[[drone]]
id = 3
connected_node_ids = [1, 2, 4, 5, 6, 11]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [3, 6, 9, 13]
pdr = 0.28

[[drone]]
id = 5
connected_node_ids = [3, 8, 11]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [3, 4, 7 ,10, 12]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [6, 10, 12]
pdr = 0.23

[[client]]
id = 8
connected_drone_ids = [1, 5]

[[server]]
id = 9
connected_drone_ids = [2, 4]

[[server]]
id = 10
connected_drone_ids = [6, 7]

[[server]]
id = 11
connected_drone_ids = [3, 5]

[[server]]
id = 12
connected_drone_ids = [1, 7]

[[server]]
id = 13
connected_drone_ids = [2, 4]